version: 2.1
orbs:
  ruby: cimg/ruby@3.0.4

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.4
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

