default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: base_development

test:
  <<: *default
  database: base_test

production:
  <<: *default
  database: base_production
